### PR TITLE
Unify categories shown in header with these on Category page

### LINKED ISSUE #172: Unify categories shown in header with these on Category page
## Current behavior

Currently in header there are different categories than in sidebar on Category page.

categories

## Expected behavior

Categories in header are the same as categories in Category page.

## Steps to reproduce the issue

Just open Category page.

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

### PR DESCRIPTION
**Pull request by psmyrek**
### Related Issues

Closes #172 

### Short Description and Why It's Useful

This change unifies categories in header and in the sidebar. Also number of products in given category is not shown if `product_count` is 0 - the same as in _Filters_ sidebar.

### Screenshots of Visual Changes before/after (If There Are Any)

categories

categories

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: pages/Category.vue [hunk 1]
```diff
@@ -309,7 +309,26 @@ export default {
...
+            position: 0
+          };
+
+          return {
+            ...this.prepareCategoryMenuItem(category),
+            items: [this.prepareCategoryMenuItem(viewAllMenuItem)]
+              .concat(
+                category.children_data.map(childCategory => this.prepareCategoryMenuItem(
+                  this.getCategories.find(category => category.id === childCategory.id)
+                ))
```
Comment (gibkigonzo) [inline pages/Category.vue]: can you add here `.filter(Boolean)` to remove undefined from array? 
`prepareCategoryMenuItem` can return undefined

Comment (psmyrek) [reply pages/Category.vue]: Sure, done  👍
