### PR TITLE
Fixed language switcher showing undefined values

### LINKED ISSUE #175: Language switcher shows "undefined" values
## Current behavior

Language switcher shows `undefined` values instead of country and language codes.

footer

## Expected behavior

Language switcher shows valid country and language codes.

## Steps to reproduce the issue

Open app and scroll to the bottom to see footer.

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

### PR DESCRIPTION
**Pull request by psmyrek**
### Related Issues

Closes #175 

### Short Description and Why It's Useful

This PR fixes language switcher to show valid country and language codes.

### Screenshots of Visual Changes before/after (If There Are Any)

footer

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: components/core/blocks/Switcher/LanguageSwitcher.vue [hunk 1]
```diff
@@ -8,14 +8,13 @@
...
 
 <script>
+import config from 'config';
 import { currentStoreView } from '@vue-storefront/core/lib/multistore';
 const ModalSwitcher = () =>
   import(
     /* webpackChunkName: "vsf-languages-modal" */ 'theme/components/core/blocks/Switcher/Language'
   );
 
-const { i18n = {} } = currentStoreView();
```
Comment (psmyrek) [inline components/core/blocks/Switcher/LanguageSwitcher.vue]: When this line was executed, `currentStoreView()` returned empty object (without `i18n` key) so `i18n` constant was assigned to `{}`.
