### PR TITLE
SSR mismatch in bottom navigation

### LINKED ISSUE #354: SSR mismatch in bottom navigation
## Current behavior

There is SSR mismatch on all pages in bottom navigation.

mis

## Expected behavior

SSR content should match client-side virtual DOM.

## Steps to reproduce the issue

1. Open any page in dev build.
2. Check console errors: there is SSR mismatch.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: any
- OS: any
- Code Version: 1.0-rc.1

### PR DESCRIPTION
**Pull request by psmyrek**
### Related Issues

Closes #354

### Short Description and Why It's Useful

This PR fixes SSR mismatch on every page in Capybara theme. It was caused by Storefront UI lib, and in latest release it does not occur anymore.
In this PR also some minor fixes were introduced after some breaking changes from Storefront UI library.

### Screenshots of Visual Changes before/after (If There Are Any)

No visual changes.

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: components/molecules/m-review-list.vue [hunk 1]
```diff
@@ -60,6 +60,16 @@ export default {
     setCurrentPage (newPage) {
       this.currentPage = newPage
     }
+  },
+  watch: {
+    $route: {
+      immediate: true,
+      handler (to, from) {
+        if (to.query.reviewPage) {
+          this.setCurrentPage(to.query.reviewPage);
```
Comment (gibkigonzo) [inline components/molecules/m-review-list.vue:69]: maybe add default `1` if query doesn't exist?
