### PR TITLE
Tabs on the product page are not reset properly

### LINKED ISSUE #228: Tabs on the product page are not reset properly
## Current behavior
If the user switches to `Read reviews`,  then each newly viewed PDP page will display a view with reviews, instead of displaying 'Description' by default

## Expected behavior
By default, first tab (Description in our case) should be opened

## Steps to reproduce the issue
1. Go to any PDP
2. Switch to "Read reviews"
3. Change PDP

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Environment details
- Browser: All
- OS: All
- Code Version: All

## Additional information
No additional information

### PR DESCRIPTION
**Pull request by psmyrek**
### Related Issues

Closes #228 

### Short Description and Why It's Useful

After opening product page always first tab with description will be shown.

### Screenshots of Visual Changes before/after (If There Are Any)

No visual changes.

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: components/molecules/m-product-additional-info.vue [hunk 1]
```diff
@@ -55,16 +54,8 @@ export default {
...
-      let counter = 0
-      this.$children[0].$children.forEach(tab => {
-        counter++
-        if (tab._uid === index) {
-          this.$store.commit('ui/setActiveProductTab', counter);
-        }
-      })
-    }
+  destroyed () {
+    this.$store.commit('ui/setActiveProductTab', 1);
```
Comment (gibkigonzo) [inline components/molecules/m-product-additional-info.vue:58]: there is no `this` with component scope in destroyed hook, please move it to beforeDestroy

Comment (psmyrek) [reply components/molecules/m-product-additional-info.vue:58]: Done, thanks.
