### PR TITLE
fix: add pick function to update profile method

### LINKED ISSUE #510: Impossible to update user's personal data
## Current behavior

When you are trying to same modified user's personal data - API throws an error: 
```
{"code":500,"result":[{"keyword":"additionalProperties","dataPath":".customer","schemaPath":"#/properties/customer/additionalProperties","params":{"additionalProperty":"id"},"message":"should NOT have additional properties"}]}
```

## Expected behavior

It should work.

## Steps to reproduce the issue

1. Open: https://capybara.storefrontcloud.io/
2. Sign in
3. Open: https://capybara.storefrontcloud.io/my-account
4. Change your name
5. Click Update personal data
6. API will throw an error

## How to fix it
In methods updatePersonalData of component/molecules/m-update-personal-data.vue replace `let updateProfile...` to:
```js
let updatedProfile = pick(JSON.parse(JSON.stringify(this.$store.state.user.current)), [...config.users.allowModification, 'default_billing'])
```
Remember about import config & pick at the top of file:
```js
import config from 'config';
import pick from 'lodash-es/pick';
```

### PR DESCRIPTION
**Pull request by AdamPawlinski**
…a change

### Related Issues
Closes #510 

### Screenshots of Visual Changes before/after (If There Are Any)
image

**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: components/molecules/m-update-personal-data.vue [hunk 1]
```diff
@@ -76,7 +78,7 @@ export default {
         });
         return;
       }
-      let updatedProfile = JSON.parse(JSON.stringify(this.$store.state.user.current))
+      let updatedProfile = pick(JSON.parse(JSON.stringify(this.$store.state.user.current)), [...config.users.allowModification, 'default_billing'])
```
Comment (gibkigonzo) [inline components/molecules/m-update-personal-data.vue:81]: change it to
`let updatedProfile = pick(JSON.parse(JSON.stringify(this.$store.state.user.current)), config.users.allowModification)`
it's fixed in 1.12.3 in core files

Comment (gibkigonzo) [reply components/molecules/m-update-personal-data.vue:81]: https://github.com/DivanteLtd/vue-storefront/pull/4929/files#diff-99fb126f4b6264f0d769dab6ec4a3720R92

Comment (AdamPawlinski) [reply components/molecules/m-update-personal-data.vue]: Changed.

**Review by gibkigonzo — APPROVED** [review]

**Review by Fifciu — APPROVED** [review]
