### PR TITLE
198/product variants images

### LINKED ISSUE #198: Product image is not changed after changing color
## Current behavior

Product image is not changed after changing color.

## Expected behavior

Product image should be changed after changing color.

## Steps to reproduce the issue

Open https://capybara.storefrontcloud.io/women/tops-women/tanks-women/bras-and-tanks-26/zoe-tank-1705.html?childSku=WT02-XS-Green and change color - first image is not changed and shows previous color.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

### PR DESCRIPTION
**Pull request by qiqqq**
### Related Issues

Closes #198

### Short Description and Why It's Useful

These changes resolve problems witch changing product variant image

### Screenshots of Visual Changes before/after (If There Are Any)

No visual changes

### Contribution and Currently Important Rules Acceptance

- [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: components/molecules/m-product-gallery.vue [hunk 1]
```diff
@@ -57,11 +55,19 @@ export default {
...
+          if (
+            typeof image.id !== 'undefined' &&
+            typeof image.id[key] !== 'undefined' &&
+            image.id[key] !== value.id
+          ) {
+            selectThis = false
+          }
+        }
+        return selectThis
+      })
```
Comment (psmyrek) [inline components/molecules/m-product-gallery.vue]: I'm not sure but this logic will not find partially matched product configurations, i.e. it will not find black image if configuration will be size 36 and color black -- in case there is no dedicated image for this configuration  🤔

Comment (qiqqq) [reply components/molecules/m-product-gallery.vue]: You are right. I fixed this.

File: components/molecules/m-product-gallery.vue [hunk 2]
```diff
@@ -57,11 +55,19 @@ export default {
...
+        for (const [key, value] of Object.entries(this.configuration)) {
+          if (
+            typeof image.id !== 'undefined' &&
+            typeof image.id[key] !== 'undefined' &&
+            image.id[key] !== value.id
+          ) {
+            selectThis = false
+          }
+        }
+        return selectThis || (image.id && image.id.color === this.configuration.color.id)
```
Comment (psmyrek) [inline components/molecules/m-product-gallery.vue]: Now it will return first variant image that matches only the color, regardless of any other images - even if they fit better (because they may contain more matching properties to current product configuration).

If it should work like that then it's fine, but in that case the whole logic for `variantImage` could be simplified: there is no need to iterate over all properties in current configuration.

Comment (qiqqq) [reply components/molecules/m-product-gallery.vue]: Fixed
